apiVersion: v1
kind: Pod
metadata:
  name: stress-demo
  namespace: demo-app
spec:
  containers:
  - name: stress
    image: polinux/stress:latest
    command: ["stress", "--vm", "1", "--vm-bytes", "64M", "--cpu", "1"]
    resources:
      limits:
        cpu: "50m"
        memory: "32Mi"
      requests:
        cpu: "50m"
        memory: "32Mi"
 